database:
  host: localhost
  port: 3306
  name: rnkm-db
  username: root
  password: root

redis:
  host: localhost:6379
  password: ""

app:
  port: 3001
  debug: true
  baan_cache_ttl: 900
  number_of_baan: 3

service:
  file: localhost:3003
